-- Populate blog_tags table with essential HVAC and air filter tags
INSERT INTO public.blog_tags (name, slug) VALUES
('MERV 8', 'merv-8'),
('MERV 11', 'merv-11'),
('MERV 13', 'merv-13'),
('MERV 16', 'merv-16'),
('HEPA Filters', 'hepa-filters'),
('Carbon Filters', 'carbon-filters'),
('Pleated Filters', 'pleated-filters'),
('Fiberglass Filters', 'fiberglass-filters'),
('Electrostatic Filters', 'electrostatic-filters'),
('Pet Allergies', 'pet-allergies'),
('Spring Allergies', 'spring-allergies'),
('Indoor Air Quality', 'indoor-air-quality'),
('HVAC Maintenance', 'hvac-maintenance'),
('Filter Replacement', 'filter-replacement'),
('Air Purification', 'air-purification'),
('Dust Control', 'dust-control'),
('Pollen Control', 'pollen-control'),
('Smoke Filtration', 'smoke-filtration'),
('Energy Efficiency', 'energy-efficiency'),
('Filter Sizing', 'filter-sizing'),
('Filter Comparison', 'filter-comparison'),
('Home Improvement', 'home-improvement'),
('Allergen Reduction', 'allergen-reduction'),
('Filter Testing', 'filter-testing'),
('HVAC Systems', 'hvac-systems'),
('Filter Installation', 'filter-installation'),
('Air Quality Tips', 'air-quality-tips'),
('Respiratory Health', 'respiratory-health'),
('Filter Technology', 'filter-technology'),
('Seasonal Filters', 'seasonal-filters')
ON CONFLICT (slug) DO NOTHING;