// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asplzhzieqwfqpemqelx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzcGx6aHppZXF3ZnFwZW1xZWx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDQyNDEsImV4cCI6MjA2OTIyMDI0MX0.W7bEHo2wQt-OQ97BkcL4SjoxYdTWWBvIYX_Rg-fUj4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});